name: pvpWorld
version: '${version}'
main: org.tofu.pvpWorld.PvpWorld
api-version: '1.21'
commands:
  pvpworld:
    description: PVP WORLDの情報・ヘルプ・お知らせを表示します
    usage: /pvpworld [help|command|notice|op|actions]
